/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-low": "#f3f4f5",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "primary": "#003461",
        "secondary-container": "#41befd",
        "on-tertiary-fixed": "#321300",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d3e4ff",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#27609d",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#424750",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-primary-fixed": "#001c38",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed-dim": "#81cfff",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#c2c6d1",
        "on-secondary-fixed": "#001e2d",
        "inverse-primary": "#a3c9ff",
        "surface-container": "#edeeef",
        "secondary-fixed": "#c6e7ff",
        "background": "#f8f9fa",
        "secondary": "#00658d",
        "tertiary-fixed": "#ffdbc8",
        "on-primary-fixed-variant": "#004882",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#ffb68b",
        "surface-variant": "#e1e3e4",
        "outline": "#727781",
        "on-primary": "#ffffff",
        "on-secondary-container": "#004b69",
        "on-primary-container": "#8abcff",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "on-error": "#ffffff",
        "primary-container": "#004b87",
        "tertiary-container": "#793701",
        "primary-fixed-dim": "#a3c9ff",
        "on-tertiary-fixed-variant": "#753400",
        "tertiary": "#572500",
        "on-tertiary-container": "#ffa46a",
        "surface-container-high": "#e7e8e9",
        "on-secondary-fixed-variant": "#004c6b"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "boxShadow": {
        "card-sm":     "0 2px 8px rgba(0,52,97,0.07)",
        "card":        "0 4px 20px rgba(0,52,97,0.10)",
        "card-lg":     "0 20px 40px -10px rgba(0,52,97,0.10)",
        "card-xl":     "0 25px 50px -12px rgba(0,75,135,0.20)",
        "id-card":     "0 8px 32px rgba(0,52,97,0.35)",
        "btn-primary": "0 4px 15px rgba(0,52,97,0.30)",
        "btn-cta":     "0 4px 16px rgba(0,101,141,0.30)",
        "card-hover":  "0 8px 28px rgba(0,52,97,0.15)"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
